<?xml version="1.0" encoding="utf-8"?><Database Name="Northwind" Class="NorthwindTradersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local);Initial Catalog=Northwind;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="NorthwindTradersV3LinqToSql.Properties.Settings" SettingsPropertyName="NorthwindConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Categories">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Categories_Products" Member="Products" ThisKey="CategoryID" OtherKey="CategoryID" Type="Products" />
    </Type>
  </Table>
  <Table Name="dbo.Territories" Member="Territories">
    <Type Name="Territories">
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryDescription" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Territories_EmployeeTerritories" Member="EmployeeTerritories" ThisKey="TerritoryID" OtherKey="TerritoryID" Type="EmployeeTerritories" />
      <Association Name="Region_Territories" Member="Region" ThisKey="RegionID" OtherKey="RegionID" Type="Region" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerCustomerDemo" Member="CustomerCustomerDemo">
    <Type Name="CustomerCustomerDemo">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CustomerDemographics_CustomerCustomerDemo" Member="CustomerDemographics" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerDemographics" IsForeignKey="true" />
      <Association Name="Customers_CustomerCustomerDemo" Member="Customers" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerDemographics" Member="CustomerDemographics">
    <Type Name="CustomerDemographics">
      <Column Name="CustomerTypeID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerDesc" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="CustomerDemographics_CustomerCustomerDemo" Member="CustomerCustomerDemo" ThisKey="CustomerTypeID" OtherKey="CustomerTypeID" Type="CustomerCustomerDemo" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customers">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Customers_CustomerCustomerDemo" Member="CustomerCustomerDemo" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerCustomerDemo" />
      <Association Name="Customers_Orders" Member="Orders" ThisKey="CustomerID" OtherKey="CustomerID" Type="Orders" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employees">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TitleOfCourtesy" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ReportsTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhotoPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Employees_Employees" Member="Employees2" ThisKey="EmployeeID" OtherKey="ReportsTo" Type="Employees" />
      <Association Name="Employees_EmployeeTerritories" Member="EmployeeTerritories" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeTerritories" />
      <Association Name="Employees_Orders" Member="Orders" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Orders" />
      <Association Name="Employees_Employees" Member="Employees1" ThisKey="ReportsTo" OtherKey="EmployeeID" Type="Employees" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTerritories" Member="EmployeeTerritories">
    <Type Name="EmployeeTerritories">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Employees_EmployeeTerritories" Member="Employees" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employees" IsForeignKey="true" />
      <Association Name="Territories_EmployeeTerritories" Member="Territories" ThisKey="TerritoryID" OtherKey="TerritoryID" Type="Territories" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order Details]" Member="Order_Details">
    <Type Name="Order_Details">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Orders_Order_Details" Member="Orders" ThisKey="OrderID" OtherKey="OrderID" Type="Orders" IsForeignKey="true" />
      <Association Name="Products_Order_Details" Member="Products" ThisKey="ProductID" OtherKey="ProductID" Type="Products" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Orders_Order_Details" Member="Order_Details" ThisKey="OrderID" OtherKey="OrderID" Type="Order_Details" />
      <Association Name="Customers_Orders" Member="Customers" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customers" IsForeignKey="true" />
      <Association Name="Employees_Orders" Member="Employees" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employees" IsForeignKey="true" />
      <Association Name="Shippers_Orders" Member="Shippers" ThisKey="ShipVia" OtherKey="ShipperID" Type="Shippers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Products">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityPerUnit" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UnitsOnOrder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReorderLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Discontinued" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Products_Order_Details" Member="Order_Details" ThisKey="ProductID" OtherKey="ProductID" Type="Order_Details" />
      <Association Name="Categories_Products" Member="Categories" ThisKey="CategoryID" OtherKey="CategoryID" Type="Categories" IsForeignKey="true" />
      <Association Name="Suppliers_Products" Member="Suppliers" ThisKey="SupplierID" OtherKey="SupplierID" Type="Suppliers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Region" Member="Region">
    <Type Name="Region">
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegionDescription" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Region_Territories" Member="Territories" ThisKey="RegionID" OtherKey="RegionID" Type="Territories" />
    </Type>
  </Table>
  <Table Name="dbo.Shippers" Member="Shippers">
    <Type Name="Shippers">
      <Column Name="ShipperID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Association Name="Shippers_Orders" Member="Orders" ThisKey="ShipperID" OtherKey="ShipVia" Type="Orders" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Suppliers">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ContactName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ContactTitle" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Region" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="HomePage" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Suppliers_Products" Member="Products" ThisKey="SupplierID" OtherKey="SupplierID" Type="Products" />
    </Type>
  </Table>
  <Table Name="dbo.VW_CLIENTESPROVEEDORES_DIRECTORIOPORCIUDAD" Member="VW_CLIENTESPROVEEDORES_DIRECTORIOPORCIUDAD">
    <Type Name="VW_CLIENTESPROVEEDORES_DIRECTORIOPORCIUDAD">
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(62)" CanBeNull="true" />
      <Column Name="Relación" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_CLIENTESPROVEEDORES_DIRECTORIOPORPAIS" Member="VW_CLIENTESPROVEEDORES_DIRECTORIOPORPAIS">
    <Type Name="VW_CLIENTESPROVEEDORES_DIRECTORIOPORPAIS">
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(62)" CanBeNull="true" />
      <Column Name="Relación" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_PRODUCTOSPORCATEGORIALISTADO" Member="VW_PRODUCTOSPORCATEGORIALISTADO">
    <Type Name="VW_PRODUCTOSPORCATEGORIALISTADO">
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="[Id Producto]" Member="Id_Producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Cantidad por unidad]" Member="Cantidad_por_unidad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Unidades en inventario]" Member="Unidades_en_inventario" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Unidades en pedido]" Member="Unidades_en_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Punto de pedido]" Member="Punto_de_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Descontinuado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_PRODUCTOSLISTAALFABETICA" Member="VW_PRODUCTOSLISTAALFABETICA">
    <Type Name="VW_PRODUCTOSLISTAALFABETICA">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Cantidad por unidad]" Member="Cantidad_por_unidad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Unidades en inventario]" Member="Unidades_en_inventario" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Unidades en pedido]" Member="Unidades_en_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Punto de pedido]" Member="Punto_de_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Descontinuado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_PRODUCTOSPORENCIMADELPRECIOPROMEDIO" Member="VW_PRODUCTOSPORENCIMADELPRECIOPROMEDIO">
    <Type Name="VW_PRODUCTOSPORENCIMADELPRECIOPROMEDIO">
      <Column Name="Fila" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_EMPLEADOS_PAIS" Method="SP_EMPLEADOS_PAIS">
    <ElementType Name="SP_EMPLEADOS_PAISResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_NOMBRES_V2" Method="SP_EMPLEADOS_NOMBRES_V2">
    <ElementType Name="SP_EMPLEADOS_NOMBRES_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_LISTAR" Method="SP_EMPLEADOS_LISTAR">
    <Parameter Name="top100" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_EMPLEADOS_LISTARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Título" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de cortesia]" Member="Título_de_cortesia" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="[Fecha de nacimiento]" Member="Fecha_de_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha de contratación]" Member="Fecha_de_contratación" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extensión" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="Notas" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Reportaa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Reporta a]" Member="Reporta_a" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_BUSCAR_V2" Method="SP_EMPLEADOS_BUSCAR_V2">
    <Parameter Name="IdIni" Parameter="idIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdFin" Parameter="idFin" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <ElementType Name="SP_EMPLEADOS_BUSCAR_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombres" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Título" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de cortesia]" Member="Título_de_cortesia" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="[Fecha de nacimiento]" Member="Fecha_de_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha de contratación]" Member="Fecha_de_contratación" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Extensión" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="Notas" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Reportaa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Reporta a]" Member="Reporta_a" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_INSERTAR_V2" Method="SP_EMPLEADOS_INSERTAR_V2">
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="TitCortesia" Parameter="titCortesia" Type="System.String" DbType="NVarChar(25)" />
    <Parameter Name="FNacimiento" Parameter="fNacimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FContratacion" Parameter="fContratacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Extension" Parameter="extension" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="Notas" Parameter="notas" Type="System.String" DbType="NText" />
    <Parameter Name="Reportaa" Parameter="reportaa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_ACTUALIZAR_V2" Method="SP_EMPLEADOS_ACTUALIZAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombres" Parameter="nombres" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="TitCortesia" Parameter="titCortesia" Type="System.String" DbType="NVarChar(25)" />
    <Parameter Name="FNacimiento" Parameter="fNacimiento" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FContratacion" Parameter="fContratacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Extension" Parameter="extension" Type="System.String" DbType="NVarChar(4)" />
    <Parameter Name="Notas" Parameter="notas" Type="System.String" DbType="NText" />
    <Parameter Name="Reportaa" Parameter="reportaa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_ELIMINAR_V2" Method="SP_EMPLEADOS_ELIMINAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CLIENTES_PAIS" Method="SP_CLIENTES_PAIS">
    <ElementType Name="SP_CLIENTES_PAISResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CLIENTES_LISTAR" Method="SP_CLIENTES_LISTAR">
    <Parameter Name="top100" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_CLIENTES_LISTARResult">
      <Column Name="Id" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de contacto]" Member="Título_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CLIENTES_BUSCAR" Method="SP_CLIENTES_BUSCAR">
    <Parameter Name="Id" Parameter="id" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <ElementType Name="SP_CLIENTES_BUSCARResult">
      <Column Name="Id" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de contacto]" Member="Título_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CLIENTES_INSERTAR_V2" Method="SP_CLIENTES_INSERTAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.String" DbType="NChar(5)" />
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CLIENTES_ACTUALIZAR_V2" Method="SP_CLIENTES_ACTUALIZAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.String" DbType="NChar(5)" />
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CLIENTES_ELIMINAR_V2" Method="SP_CLIENTES_ELIMINAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.String" DbType="NChar(5)" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CLIENTESPROVEEDORES_CIUDAD" Method="SP_CLIENTESPROVEEDORES_CIUDAD">
    <ElementType Name="SP_CLIENTESPROVEEDORES_CIUDADResult">
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CiudadPaís" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CLIENTESPROVEEDORES_PAIS" Method="SP_CLIENTESPROVEEDORES_PAIS">
    <ElementType Name="SP_CLIENTESPROVEEDORES_PAISResult">
      <Column Name="IdPaís" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(26)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_PAIS" Method="SP_PROVEEDORES_PAIS">
    <ElementType Name="SP_PROVEEDORES_PAISResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_LISTAR" Method="SP_PROVEEDORES_LISTAR">
    <Parameter Name="top100" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_PROVEEDORES_LISTARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de contacto]" Member="Título_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_BUSCAR_V2" Method="SP_PROVEEDORES_BUSCAR_V2">
    <Parameter Name="IdIni" Parameter="idIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdFin" Parameter="idFin" Type="System.Int32" DbType="Int" />
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <ElementType Name="SP_PROVEEDORES_BUSCAR_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de compañía]" Member="Nombre_de_compañía" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Título de contacto]" Member="Título_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Domicilio" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Código postal]" Member="Código_postal" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="País" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Teléfono" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_INSERTAR_V2" Method="SP_PROVEEDORES_INSERTAR_V2">
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_ACTUALIZAR_V2" Method="SP_PROVEEDORES_ACTUALIZAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Compañia" Parameter="compañia" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Titulo" Parameter="titulo" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Domicilio" Parameter="domicilio" Type="System.String" DbType="NVarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Region" Parameter="region" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="CodigoP" Parameter="codigoP" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="Pais" Parameter="pais" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="NVarChar(24)" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_ELIMINAR_V2" Method="SP_PROVEEDORES_ELIMINAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_ALL" Method="SP_PRODUCTOS_ALL">
    <Parameter Name="top100" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_PRODUCTOS_ALLResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Cantidad por unidad]" Member="Cantidad_por_unidad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Unidades en inventario]" Member="Unidades_en_inventario" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Unidades en pedido]" Member="Unidades_en_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Punto de pedido]" Member="Punto_de_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Descontinuado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Descripción de categoría]" Member="Descripción_de_categoría" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_LISTAR" Method="SP_CATEGORIAS_LISTAR">
    <Parameter Name="top100" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_CATEGORIAS_LISTARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Descripción" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_BUSCAR_V2" Method="SP_CATEGORIAS_BUSCAR_V2">
    <Parameter Name="IdIni" Parameter="idIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdFin" Parameter="idFin" Type="System.Int32" DbType="Int" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="NVarChar(15)" />
    <ElementType Name="SP_CATEGORIAS_BUSCAR_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Descripción" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_INSERTAR_V2" Method="SP_CATEGORIAS_INSERTAR_V2">
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_ACTUALIZAR_V2" Method="SP_CATEGORIAS_ACTUALIZAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.Data.Linq.Binary" DbType="Image" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_ELIMINAR_V2" Method="SP_CATEGORIAS_ELIMINAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_SELECCIONAR_V2" Method="SP_CATEGORIAS_SELECCIONAR_V2">
    <ElementType Name="SP_CATEGORIAS_SELECCIONAR_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PROVEEDORES_SELECCIONAR" Method="SP_PROVEEDORES_SELECCIONAR">
    <ElementType Name="SP_PROVEEDORES_SELECCIONARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_BUSCAR_V2" Method="SP_PRODUCTOS_BUSCAR_V2">
    <Parameter Name="IdIni" Parameter="idIni" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdFin" Parameter="idFin" Type="System.Int32" DbType="Int" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Proveedor" Parameter="proveedor" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_PRODUCTOS_BUSCAR_V2Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Cantidad por unidad]" Member="Cantidad_por_unidad" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="[Unidades en inventario]" Member="Unidades_en_inventario" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Unidades en pedido]" Member="Unidades_en_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="[Punto de pedido]" Member="Punto_de_pedido" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Descontinuado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Categoría" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="[Descripción de categoría]" Member="Descripción_de_categoría" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Proveedor" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_INSERTAR_V2" Method="SP_PRODUCTOS_INSERTAR_V2">
    <Parameter Name="Categoria" Parameter="categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Proveedor" Parameter="proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="UInventario" Parameter="uInventario" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="UPedido" Parameter="uPedido" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="PPedido" Parameter="pPedido" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Descontinuado" Parameter="descontinuado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_ELIMINAR_V2" Method="SP_PRODUCTOS_ELIMINAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_ACTUALIZAR_V2" Method="SP_PRODUCTOS_ACTUALIZAR_V2">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Proveedor" Parameter="proveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Categoria" Parameter="categoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="UInventario" Parameter="uInventario" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="UPedido" Parameter="uPedido" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="PPedido" Parameter="pPedido" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Descontinuado" Parameter="descontinuado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CLIENTES_SELECCIONAR" Method="SP_CLIENTES_SELECCIONAR">
    <ElementType Name="SP_CLIENTES_SELECCIONARResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_EMPLEADOS_SELECCIONAR" Method="SP_EMPLEADOS_SELECCIONAR">
    <ElementType Name="SP_EMPLEADOS_SELECCIONARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Empleado" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_TRANSPORTISTAS_SELECCIONAR" Method="SP_TRANSPORTISTAS_SELECCIONAR">
    <ElementType Name="SP_TRANSPORTISTAS_SELECCIONARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transportista" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CATEGORIAS_SELECCIONAR" Method="SP_CATEGORIAS_SELECCIONAR">
    <ElementType Name="SP_CATEGORIAS_SELECCIONARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(75)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PEDIDOS_LISTAR20" Method="SP_PEDIDOS_LISTAR20">
    <ElementType Name="SP_PEDIDOS_LISTAR20Result">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Fecha de pedido]" Member="Fecha_de_pedido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha requerido]" Member="Fecha_requerido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha de envío]" Member="Fecha_de_envío" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Vendedor" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="[Compañía transportista]" Member="Compañía_transportista" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Dirigido a]" Member="Dirigido_a" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PEDIDOS_BUSCAR" Method="SP_PEDIDOS_BUSCAR">
    <Parameter Name="IdInicial" Parameter="idInicial" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdFinal" Parameter="idFinal" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cliente" Parameter="cliente" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="FPedido" Parameter="fPedido" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FPedidoNull" Parameter="fPedidoNull" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FPedidoIni" Parameter="fPedidoIni" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FPedidoFin" Parameter="fPedidoFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FRequerido" Parameter="fRequerido" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FRequeridoNull" Parameter="fRequeridoNull" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FRequeridoIni" Parameter="fRequeridoIni" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FRequeridoFin" Parameter="fRequeridoFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FEnvio" Parameter="fEnvio" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FEnvioNull" Parameter="fEnvioNull" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FEnvioIni" Parameter="fEnvioIni" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FEnvioFin" Parameter="fEnvioFin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Empleado" Parameter="empleado" Type="System.String" DbType="NVarChar(31)" />
    <Parameter Name="CompañiaT" Parameter="compañiaT" Type="System.String" DbType="NVarChar(40)" />
    <Parameter Name="Dirigidoa" Parameter="dirigidoa" Type="System.String" DbType="NVarChar(40)" />
    <ElementType Name="SP_PEDIDOS_BUSCARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="[Nombre de contacto]" Member="Nombre_de_contacto" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="[Fecha de pedido]" Member="Fecha_de_pedido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha requerido]" Member="Fecha_requerido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Fecha de envío]" Member="Fecha_de_envío" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Empleado" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="[Compañía transportista]" Member="Compañía_transportista" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="[Dirigido a]" Member="Dirigido_a" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PRODUCTOS_SELECCIONAR" Method="SP_PRODUCTOS_SELECCIONAR">
    <Parameter Name="Categoria" Parameter="categoria" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_PRODUCTOS_SELECCIONARResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PEDIDOS_LISTAR1" Method="SP_PEDIDOS_LISTAR1">
    <Parameter Name="PedidoId" Parameter="pedidoId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_PEDIDOS_LISTAR1Result">
      <Column Name="CustomerID" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequiredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShipVia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Freight" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ShipName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShipAddress" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="ShipCity" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipRegion" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ShipPostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ShipCountry" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_DETALLEPEDIDOS_PRODUCTOS_LISTAR1" Method="SP_DETALLEPEDIDOS_PRODUCTOS_LISTAR1">
    <Parameter Name="PedidoId" Parameter="pedidoId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_DETALLEPEDIDOS_PRODUCTOS_LISTAR1Result">
      <Column Name="[Id Producto]" Member="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Producto" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Descuento" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_PEDIDOSDETALLE_ACTUALIZAR_V3" Method="SP_PEDIDOSDETALLE_ACTUALIZAR_V3">
    <Parameter Name="OrderId" Parameter="orderId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ProductId" Parameter="productId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="Discount" Parameter="discount" Type="System.Single" DbType="Real" />
    <Parameter Name="QuantityOld" Parameter="quantityOld" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="DiscountOld" Parameter="discountOld" Type="System.Single" DbType="Real" />
    <Parameter Name="NumRegs" Parameter="numRegs" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>